spring.application.name=petexpress-site-backend

spring.datasource.url=jdbc:sqlite:petexpress.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

server.port=${PORT:8082}

# Mercado Pago
mercadopago.access-token=${APP_USR-690590767684818-042905-c98708c38abe6870739f03a2ab22fc3a-3367643984}
mercadopago.public-key=${APP_USR-8059b69a-345f-4492-a4a2-1c9be1e67056}